AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=venkateshfiles;AccountKey=U3NuR/ASfe3OADz7NauOuazEmv0tZP+/83SNApFXT3p9n7KvGf9S6WwepFTZfEHsZU8AA7D9ifeu+AStOPAOgA==;EndpointSuffix=core.windows.net"
AZURE_CONTAINER_NAME = "resumes"

GOOGLE_API_KEY = "AIzaSyAwlJ-6BfIS3HeMPsjYU9Pc0A89lgykjuw"

PINECONE_API_KEY = "pcsk_2D2xmL_Jw6jivqDfq893gNSjWLbQnKD7mtUSikS3JtojffdQUhpy8NbxFqeL3tvEE4hKeP"
PINECONE_ENVIRONMENT = "chatbot"  
PINECONE_INDEX1 = "chatbot350"
